apiVersion: v1
kind: Service
metadata:
  name: nestjs
  namespace: default
spec:
  selector:
    app: nestjs
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: nestjs
    protocol: TCP
    port: 8080
    targetPort: 8080
