version: '3.4'
services:
  backend:
    container_name: backend
    build:
      context: .
      target: microservice1
    ports:
      - "8080:8080"
  frontend:
    container_name: frontend
    build:
      context: .
      target: frontend
    ports:
    - "80:80"
    # For nginx reverse proxy configuration remove the lines below
    # volumes:
    #   - ./conf.d:/etc/nginx/conf.d
