apiVersion: v1
kind: Service
metadata:
  name: angular
  namespace: default
spec:
  selector:
    app: angular
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: angular
    protocol: TCP
    port: 80
    nodePort: 30036
    targetPort: 80
